#!/usr/bin/env bash
#https://github.com/nekr0z/linux-on-huawei-matebook-13-2019
echo set standard performance
#turbo boost
echo -n "boost cur: "
cat /sys/devices/system/cpu/cpufreq/boost
cpupower set -t 1
echo -n "boost new: "
cat /sys/devices/system/cpu/cpufreq/boost
#max_freq
echo -n "max_freq cur: "
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
cpupower frequency-set -u 2.1GHz > /dev/null
echo -n "max_freq new: "
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
#governor
echo -n "scaling_governor cur: "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo -n "scaling_governor new: "
echo schedutil | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
#
echo -n "zapret status: "
systemctl status zapret_discord_youtube.service | grep Active | cut -w -f 3
#
echo "for stress test: stress --cpu 8"
echo "for temp monitor: watch -n 1 sensors"