#!/usr/bin/env bash
#https://github.com/nekr0z/linux-on-huawei-matebook-13-2019
echo set minimal performance
./tboost_off
./cpufreq_min
./scaling_ps
./zapret_stat
echo "for stress test : stress --cpu 8"
echo "for temp monitor : watch -n 1 sensors"
