#!/usr/bin/env bash
#https://github.com/nekr0z/linux-on-huawei-matebook-13-2019
echo set standard performance
./tboost_on
./cpufreq_max
./scaling_su
./zapret_stat
echo "for stress test : stress --cpu 8"
echo "for temp monitor : watch -n 1 sensors"
