#!/usr/bin/env bash
#/sys/class/power_supply/BAT0/charge_control_{start,end}_threshold
#  or /sys/devices/platform/huawei-wmi/charge_control_thresholds
#echo 90 | tee /sys/class/power_supply/BAT0/charge_control_end_threshold
#echo "0 90" | tee /sys/devices/platform/huawei-wmi/charge_control_thresholds