#!/usr/bin/env bash
echo -n "max cpu freq : "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#echo -n "cur " && cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq | tr -d '\n\t'
#echo -n " max " && cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#lscpu -e=CPU,MHZ
#sudo cpupower frequency-info
