#!/usr/bin/env bash
echo "cur" && cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
echo "max" && cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
lscpu -e=CPU,MHZ
#sudo cpupower frequency-info
